AWSTemplateFormatVersion: "2010-09-09"
Description: Prepare staging environment
Parameters: 
  UniqueID: 
    Type: String
    Default: yourinitials
    Description: Enter your initials in lower case as a unique identifier for components created 
    AllowedPattern: "^([a-z]|(d(?!d{0,2}.d{1,3}.d{1,3}.d{1,3})))([a-zd]|(.(?!(.|-)))|(-(?!.))){1,61}[a-zd.]$"
  LambdaFunctionsBucket:
    Type: String
    Default: mlops-bia-lambda-code-yourinitials-uniqueid
    Description: S3 Bucket containing your Lambda Functions (Should match the bucket created by the PrepPipeline stack
  ToolsAccountID:
    Type: String
    Description: AWS Account ID of the IT Tools account.
  
Resources:
  S3DataBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: BucketOwnerFullControl
      VersioningConfiguration: 
        Status: Enabled
      BucketName:
        Fn::Join:
          - ""
          - - "mlops-bia-data-"
            - !Ref UniqueID
            - "-"
            - !Select
             - 0
             - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

  AllowAccessToDevAccountRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            AWS: !Ref ToolsAccountID
          Action: sts:AssumeRole
      Policies:
        - PolicyName: crossaccountaccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource:
                  Fn::Join:
                    - ""
                    - - !GetAtt S3DataBucket.Arn
                      - "/"
              - Effect: Allow
                Action: sagemaker:*
                Resource: "*"
      RoleName:
        Fn::Join:
          - ""
          - - "AllowAccessToToolsAccountRole-"
            - !Ref UniqueID
            - "-"
            - !Select
              - 0
              - !Split
                - "-"
                - !Select
                  - 2
                  - !Split
                    - "/"
                    - !Ref "AWS::StackId"

  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: sagemaker.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName:
        Fn::Join:
          - ""
          - - "SageMakerExecutionRole-"
            - !Ref UniqueID
            - "-"
            - !Select
              - 0
              - !Split
                - "-"
                - !Select
                  - 2
                  - !Split
                    - "/"
                    - !Ref "AWS::StackId"

Outputs:
      S3DataBucket:
        Description: The ID of the S3 Bucket for model training and test data
        Value: !Ref S3DataBucket
